# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(default='ex', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
