# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170131_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
