# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20170207_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='url',
            field=models.URLField(),
        ),
    ]
